# Generated by Django 5.1 on 2024-08-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], max_length=4)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volatility', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_to_maturity', models.DecimalField(decimal_places=4, max_digits=5)),
                ('risk_free_rate', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
